apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-no-mtls
  labels:
    type: workshop
spec:
  targets:
  - name: mysql     # The name of *your* K8s Service
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-strict-no-mtls
spec:
  host: mysql     # The name of *your* K8s Service
  trafficPolicy:
    tls:
      mode: DISABLE

