apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-v1
  labels:
    app: guestbook-ui
    version: "1.0-infinispan"
    visualize: "true"
    type: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
      version: "1.0-infinispan"
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-ui
        version: "1.0-infinispan"
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: helloworld-service,guestbook-service,redis
        sidecar.istio.io/inject: 'true'
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: guestbook-ui
        image: clamer/guestbook-ui:1.1-infinispan
        imagePullPolicy: Always
        env:
        - name: APPLICATION_NAME
          value: cache-service
        - name: APPLICATION_URL
          value: cache-service.demo-infinispan
        - name: SASL_MECHANISM
          value: DIGEST-MD5
        - name: USE_AUTH
          value: 'true'
        - name: USE_SSL
          value: 'true'
        - name: INFINISPAN_AUTH_REALM
          value: ApplicationRealm
        - name: INFINISPAN_REMOTE_USERNAME
          valueFrom:
            secretKeyRef:
              name: cache-service
              key: application-user
        - name: INFINISPAN_REMOTE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cache-service
              key: application-password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1500m
            memory: 1000Mi
