apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  ##replace the namespace
  host: "*.istio-demo-app.svc.cluster.local" 
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
